import os
import json
import time
import io
from PIL import Image
from google import genai
from google.genai import types

def main():
    # Setup directories
    backend_dir = os.path.dirname(os.path.realpath(__file__))
    posters_state_file = os.path.join(backend_dir, 'poster_prompts_state.json')
    assets_dir = os.path.join(backend_dir, 'assets', 'posters')
    
    # Target poster details
    pun_id = "quote_006_1778210473628"
    original_filename = "temp_work_poster_new_1778767429843.png"
    original_filepath = os.path.join(assets_dir, original_filename)
    
    # Initialize Gemini API Client
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("CRITICAL ERROR: GEMINI_API_KEY environment variable is not set.")
        return
        
    client = genai.Client(api_key=api_key)
    
    if not os.path.exists(original_filepath):
        print(f"CRITICAL ERROR: Original poster not found at {original_filepath}")
        return
        
    print(f"Step 1: Loading original poster image from: {original_filepath}")
    original_image = Image.open(original_filepath)
    
    # Stage 1: Analyze existing poster using Gemini 3.1 Pro
    print("\nStep 2: Sending original image to Gemini 3.1 Pro for style & layout analysis...")
    analysis_prompt = """
    You are a master graphic designer and professional movie poster illustrator.
    We have an existing square (1:1) parody movie poster for a film called 'Temp-work'.
    We want to reformat it as a standard vertical movie poster (2:3 aspect ratio).
    
    Analyze the attached image in detail:
    1. Visual Style: Specifically the 1960s Saul Bass minimalist poster design, jagged paper-cutout shapes, abstract symbolism.
    2. Color Scheme: The exact color palette (contrasting red, black, and white).
    3. Composition: The central figure (disgruntled temporary employee) and corporate elements (intercom/microphone/speakers).
    4. Typography: The exact placement, font style, and scaling of the movie title text "Temp-work".
    
    Generate a highly detailed, professional prompt for an image generator (Imagen 3) to replicate this exact poster look and feel, composition, character layout, color palette, and typography, but optimized for a vertical 2:3 movie poster format.
    
    The prompt must end with this instruction: 'CRITICAL INSTRUCTION: You must prominently feature the exact text "Temp-work" as the movie title on the poster in a stylized, bold, paper-cutout font. Do not include any studio shields, globes, or branding.'
    
    Return only the optimized prompt string. Do not include markdown code block formatting.
    """
    
    try:
        analysis_response = client.models.generate_content(
            model='models/gemini-3.1-pro-preview',
            contents=[original_image, analysis_prompt]
        )
        refined_prompt = analysis_response.text.strip()
        print("\n--- Optimized Prompt Generated by Gemini 3.1 Pro ---")
        print(refined_prompt)
        print("-----------------------------------------------------")
    except Exception as e:
        print(f"Error during Gemini 3.1 Pro image analysis: {e}")
        print("Falling back to pre-defined prompt...")
        refined_prompt = (
            "Generate a vertical movie poster illustration for a spoof movie called 'Temp-work' (Parodying a famous classic film). "
            "Create this entirely in the style of: 1960s Saul Bass minimalist poster design, jagged paper-cutout shapes, abstract symbolism, "
            "stark contrasting colors (heavy red, black, and white). It must look like an illustration, NOT a photograph or a cinematic movie still. "
            "The central focus should be: A disgruntled temporary employee hijacks the corporate intercom system to furiously denounce the Human Resources department. "
            "CRITICAL INSTRUCTION: You must prominently feature the exact text \"Temp-work\" as the movie title on the poster in a stylized, bold, "
            "paper-cutout font. Do not include any studio shields, globes, or branding."
        )

    # Stage 2: Generate reformatted vertical poster using Imagen 4
    print("\nStep 3: Generating vertical poster with Imagen 4...")
    result_image = None
    
    # Try 2:3 aspect ratio first
    try:
        print("Attempting generation with 2:3 aspect ratio...")
        response = client.models.generate_images(
            model='models/imagen-4.0-generate-001',
            prompt=refined_prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                output_mime_type='image/png',
                aspect_ratio='2:3',
            )
        )
        if response.generated_images:
            result_image = response.generated_images[0]
            print("Successfully generated 2:3 poster using models/imagen-4.0-generate-001!")
    except Exception as e:
        print(f"2:3 aspect ratio failed or not supported by API: {e}")
        
    # Fallback to 3:4 if 2:3 is not supported or failed
    if not result_image:
        try:
            print("Attempting fallback generation with 3:4 aspect ratio...")
            response = client.models.generate_images(
                model='models/imagen-4.0-generate-001',
                prompt=refined_prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    output_mime_type='image/png',
                    aspect_ratio='3:4',
                )
            )
            if response.generated_images:
                result_image = response.generated_images[0]
                print("Successfully generated 3:4 poster using models/imagen-4.0-generate-001!")
        except Exception as fallback_e:
            print(f"3:4 aspect ratio fallback also failed: {fallback_e}")

    # Stage 3: Save generated image and update JSON database
    if result_image:
        new_filename = f"temp_work_poster_vertical_{int(time.time())}.png"
        new_filepath = os.path.join(assets_dir, new_filename)
        
        print(f"\nStep 4: Saving generated image to {new_filepath}")
        image_bytes = Image.open(io.BytesIO(result_image.image.image_bytes))
        image_bytes.save(new_filepath)
        
        # Update poster_prompts_state.json
        if os.path.exists(posters_state_file):
            print("Step 5: Updating poster_prompts_state.json database...")
            with open(posters_state_file, 'r', encoding='utf-8') as f:
                state_data = json.load(f)
                
            for item in state_data:
                if item.get('pun_id') == pun_id:
                    item['image_path'] = f"/assets/posters/{new_filename}"
                    item['prompt'] = refined_prompt
                    print(f"Database entry for {pun_id} updated successfully to: {item['image_path']}")
                    break
                    
            with open(posters_state_file, 'w', encoding='utf-8') as f:
                json.dump(state_data, f, indent=2)
                
        # Update production_daily_games.json
        prod_games_file = os.path.join(backend_dir, 'production_daily_games.json')
        if os.path.exists(prod_games_file):
            print("Step 6: Updating production_daily_games.json database...")
            with open(prod_games_file, 'r', encoding='utf-8') as f:
                prod_data = json.load(f)
                
            for item in prod_data:
                if item.get('puzzle_id') == f"puz_{pun_id}" or item.get('boss_id') == f"boss_{pun_id}":
                    item['boss_poster_url'] = f"/assets/posters/{new_filename}"
                    print(f"Production Daily Games entry updated successfully to: {item['boss_poster_url']}")
                    break
                    
            with open(prod_games_file, 'w', encoding='utf-8') as f:
                json.dump(prod_data, f, indent=2)
                
        print("\n[SUCCESS] Poster reformatting successfully completed!")
        print(f"New Poster Asset: /assets/posters/{new_filename}")
    else:
        print("\nCRITICAL ERROR: Failed to generate vertical poster image.")

if __name__ == "__main__":
    main()
